version: '3.8'
services:
  api:
    image: api:latest
    container_name: api_backend
    ports:
      - '4000:4000'
  client:
    image: client:latest
    container_name: client_frontend
    ports:
      - '3000:3000'